//! Generated protobuf bindings of the plugin contract.
//!
//! The proto files of the plugin-spec repository are the source of truth for
//! the wire protocol. Everything in `v1` and `registry` is generated by
//! `cargo xtask generate`, do not edit it. The hand written types of
//! [`protocol`](crate::protocol) mirror these messages, and a test fails when
//! they drift.
//!
//! The plugin runtime does not exchange these types with your handlers. The
//! gRPC transport decodes a request into the JSON params the stdio transport
//! carries and encodes a result the same way, through the codecs in
//! [`registry`], so one handler serves both transports.

pub mod registry;
pub mod wkt;

/// Messages of package `nginxui.plugin.v1`.
#[allow(
    missing_docs,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    rustdoc::all,
    unused_qualifications,
    unreachable_pub
)]
pub mod v1 {
    include!("nginxui.plugin.v1.rs");
    include!("nginxui.plugin.v1.serde.rs");
}

/// Serialized `FileDescriptorSet` of the contract package, without imports
/// and without method options. Tests use it to check the hand written types.
pub const DESCRIPTORS: &[u8] = include_bytes!("descriptors.bin");

/// Codecs between protobuf bytes and the protobuf JSON mapping, used by
/// the registry.
pub(crate) mod codec {
    use prost::Message;
    use serde::de::DeserializeOwned;
    use serde::Serialize;
    use serde_json::Value;

    /// Decodes protobuf bytes and maps the message to JSON.
    pub(crate) fn to_json<M: Message + Default + Serialize>(bytes: &[u8]) -> Result<Value, String> {
        let message = M::decode(bytes).map_err(|e| format!("decode message: {e}"))?;
        serde_json::to_value(&message).map_err(|e| format!("encode message as JSON: {e}"))
    }

    /// Maps JSON to a message and encodes it, dropping unknown members. Null
    /// stands for the empty message.
    pub(crate) fn from_json<M: Message + Default + DeserializeOwned>(
        value: &Value,
    ) -> Result<Vec<u8>, String> {
        if value.is_null() {
            return Ok(M::default().encode_to_vec());
        }
        let message: M = serde_json::from_value(value.clone())
            .map_err(|e| format!("decode JSON into message: {e}"))?;
        Ok(message.encode_to_vec())
    }
}
