// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlocklistFetchRequest {
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlocklistFetchResponse {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<BlocklistEntry>,
    #[prost(int32, tag = "2")]
    pub ttl_seconds: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BlocklistEntry {
    #[prost(string, tag = "1")]
    pub cidr: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeployValidateRequest {
    #[prost(string, tag = "1")]
    pub kind: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeployValidateResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeployPushRequest {
    #[prost(string, tag = "1")]
    pub kind: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "3")]
    pub certificate: ::core::option::Option<DeployCertificate>,
    #[prost(bool, tag = "4")]
    pub dry_run: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeployCertificate {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub certificate_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub private_key_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub chain_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub not_after: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeployPushResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoveryResolveRequest {
    #[prost(string, tag = "1")]
    pub provider: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "3")]
    pub service: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoveryResolveResponse {
    #[prost(message, repeated, tag = "1")]
    pub targets: ::prost::alloc::vec::Vec<DiscoveryTarget>,
    #[prost(int32, tag = "2")]
    pub ttl_seconds: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DiscoveryTarget {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub port: i32,
    #[prost(int32, tag = "3")]
    pub weight: i32,
    #[prost(string, repeated, tag = "4")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dns01PresentRequest {
    #[prost(string, tag = "1")]
    pub provider: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<crate::pb::wkt::Struct>,
    #[prost(string, tag = "4")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub fqdn: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub effective_fqdn: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub key_auth: ::prost::alloc::string::String,
    #[prost(bool, tag = "10")]
    pub dry_run: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Dns01PresentResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dns01CleanupRequest {
    #[prost(string, tag = "1")]
    pub provider: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<crate::pb::wkt::Struct>,
    #[prost(string, tag = "4")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub fqdn: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub effective_fqdn: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub key_auth: ::prost::alloc::string::String,
    #[prost(bool, tag = "10")]
    pub dry_run: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Dns01CleanupResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dns01OptionsRequest {
    #[prost(string, tag = "1")]
    pub provider: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<crate::pb::wkt::Struct>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Dns01OptionsResponse {
    #[prost(int32, tag = "1")]
    pub propagation_timeout_seconds: i32,
    #[prost(int32, tag = "2")]
    pub polling_interval_seconds: i32,
    #[prost(int32, tag = "3")]
    pub sequential_interval_seconds: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dns01CheckRequest {
    #[prost(string, tag = "1")]
    pub provider: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<crate::pb::wkt::Struct>,
    #[prost(string, tag = "4")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub fqdn: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub key_auth: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Dns01CheckResponse {
    #[prost(bool, tag = "1")]
    pub ready: bool,
    #[prost(string, tag = "2")]
    pub effective_fqdn: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub detail: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dns01ValidateRequest {
    #[prost(string, tag = "1")]
    pub provider: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Dns01ValidateResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PluginError {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<crate::pb::wkt::Struct>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvalidConfigData {
    #[prost(string, tag = "1")]
    pub field: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    Unspecified = 0,
    ParseError = -32700,
    InvalidRequest = -32600,
    MethodNotFound = -32601,
    InvalidParams = -32602,
    InternalError = -32000,
    PermissionDenied = -32001,
    Unsupported = -32002,
    InvalidConfig = -32003,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ERROR_CODE_UNSPECIFIED",
            Self::ParseError => "ERROR_CODE_PARSE_ERROR",
            Self::InvalidRequest => "ERROR_CODE_INVALID_REQUEST",
            Self::MethodNotFound => "ERROR_CODE_METHOD_NOT_FOUND",
            Self::InvalidParams => "ERROR_CODE_INVALID_PARAMS",
            Self::InternalError => "ERROR_CODE_INTERNAL_ERROR",
            Self::PermissionDenied => "ERROR_CODE_PERMISSION_DENIED",
            Self::Unsupported => "ERROR_CODE_UNSUPPORTED",
            Self::InvalidConfig => "ERROR_CODE_INVALID_CONFIG",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ERROR_CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "ERROR_CODE_PARSE_ERROR" => Some(Self::ParseError),
            "ERROR_CODE_INVALID_REQUEST" => Some(Self::InvalidRequest),
            "ERROR_CODE_METHOD_NOT_FOUND" => Some(Self::MethodNotFound),
            "ERROR_CODE_INVALID_PARAMS" => Some(Self::InvalidParams),
            "ERROR_CODE_INTERNAL_ERROR" => Some(Self::InternalError),
            "ERROR_CODE_PERMISSION_DENIED" => Some(Self::PermissionDenied),
            "ERROR_CODE_UNSUPPORTED" => Some(Self::Unsupported),
            "ERROR_CODE_INVALID_CONFIG" => Some(Self::InvalidConfig),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventsOnRequest {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<crate::pb::wkt::Value>,
    #[prost(uint32, tag = "3")]
    pub ts: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventsOnResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostLogRequest {
    #[prost(string, tag = "1")]
    pub level: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub fields: ::core::option::Option<crate::pb::wkt::Struct>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostLogResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostKvGetRequest {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostKvGetResponse {
    #[prost(message, optional, tag = "1")]
    pub value: ::core::option::Option<crate::pb::wkt::Value>,
    #[prost(bool, tag = "2")]
    pub found: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostKvSetRequest {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<crate::pb::wkt::Value>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostKvSetResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostKvDeleteRequest {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostKvDeleteResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostKvListRequest {
    #[prost(string, tag = "1")]
    pub prefix: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostKvListResponse {
    #[prost(string, repeated, tag = "1")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostSettingsGetRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostSettingsGetResponse {
    #[prost(message, optional, tag = "1")]
    pub settings: ::core::option::Option<crate::pb::wkt::Struct>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostI18nLocaleRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostI18nLocaleResponse {
    #[prost(string, tag = "1")]
    pub locale: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCredentialsGetRequest {
    #[prost(string, tag = "1")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostCredentialsGetResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub provider_code: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "4")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCronRegisterRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub schedule: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub method: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCronRegisterResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCronUnregisterRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCronUnregisterResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostNotifyRequest {
    #[prost(string, tag = "1")]
    pub level: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub content: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub details: ::core::option::Option<crate::pb::wkt::Value>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostNotifyResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostMetricsSnapshotRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostMetricsSnapshotResponse {
    #[prost(message, optional, tag = "1")]
    pub snapshot: ::core::option::Option<crate::pb::wkt::Value>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostLogsListRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostLogsListResponse {
    #[prost(message, repeated, tag = "1")]
    pub logs: ::prost::alloc::vec::Vec<HostLogFile>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostLogFile {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub config_file: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostActivitySetRequest {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub label: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub active: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostActivitySetResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostNginxSnippetPutRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostNginxSnippetPutResponse {
    #[prost(bool, tag = "1")]
    pub changed: bool,
    #[prost(string, tag = "2")]
    pub include: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostNginxSnippetDeleteRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostNginxSnippetDeleteResponse {
    #[prost(bool, tag = "1")]
    pub removed: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostNginxSnippetListRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostNginxSnippetListResponse {
    #[prost(message, repeated, tag = "1")]
    pub snippets: ::prost::alloc::vec::Vec<HostNginxSnippet>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostNginxSnippet {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub include: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostNginxConfigListRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostNginxConfigListResponse {
    #[prost(string, repeated, tag = "1")]
    pub files: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostNginxConfigGetRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostNginxConfigGetResponse {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostSitesListRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostSitesListResponse {
    #[prost(message, repeated, tag = "1")]
    pub sites: ::prost::alloc::vec::Vec<HostSite>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostSite {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub urls: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub config_file: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCertsListRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostCertsListResponse {
    #[prost(message, repeated, tag = "1")]
    pub certs: ::prost::alloc::vec::Vec<HostCert>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostCert {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "4")]
    pub auto_renew: bool,
    #[prost(string, tag = "5")]
    pub challenge_method: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub key_type: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub not_before: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub not_after: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub issuer: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpHandleRequest {
    #[prost(string, tag = "1")]
    pub method: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub query: ::prost::alloc::string::String,
    #[prost(btree_map = "string, message", tag = "4")]
    pub headers: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        crate::pb::wkt::ListValue,
    >,
    #[prost(bytes = "vec", tag = "5")]
    pub body_base64: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "6")]
    pub user: ::core::option::Option<HttpUser>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HttpUser {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpHandleResponse {
    #[prost(int32, tag = "1")]
    pub status: i32,
    #[prost(btree_map = "string, message", tag = "2")]
    pub headers: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        crate::pb::wkt::ListValue,
    >,
    #[prost(bytes = "vec", tag = "3")]
    pub body_base64: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostInfo {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub os: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub arch: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub locale: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PluginInitializeRequest {
    #[prost(message, optional, tag = "1")]
    pub host: ::core::option::Option<HostInfo>,
    #[prost(message, optional, tag = "2")]
    pub settings: ::core::option::Option<crate::pb::wkt::Struct>,
    #[prost(string, repeated, tag = "3")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginInitializeResponse {
    #[prost(int32, tag = "1")]
    pub api_version: i32,
    #[prost(string, repeated, tag = "2")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub transports: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, tag = "4")]
    pub http_port: i32,
    #[prost(int32, tag = "5")]
    pub rpc_port: i32,
    #[prost(string, tag = "6")]
    pub rpc_token: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub rpc_socket: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub http_pipe: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub rpc_pipe: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginInitializedRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginInitializedResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PluginConfigureRequest {
    #[prost(message, optional, tag = "1")]
    pub settings: ::core::option::Option<crate::pb::wkt::Struct>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginConfigureResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginPingRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginPingResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginShutdownRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginShutdownResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginExitRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginExitResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogSinkPushRequest {
    #[prost(string, tag = "1")]
    pub log_path: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub entry: ::core::option::Option<LogEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogEntry {
    #[prost(string, tag = "1")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub remote_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub request_method: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub request_uri: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub status: i32,
    #[prost(double, tag = "7")]
    pub body_bytes_sent: f64,
    #[prost(string, tag = "8")]
    pub referer: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub user_agent: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub upstream_addr: ::prost::alloc::string::String,
    #[prost(double, tag = "11")]
    pub request_time: f64,
    #[prost(double, tag = "12")]
    pub upstream_response_time: f64,
    #[prost(string, tag = "13")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub raw: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub format: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogSinkPushResponse {
    #[prost(uint32, tag = "1")]
    pub accepted: u32,
    #[prost(uint32, tag = "2")]
    pub rejected: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Manifest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub homepage_url: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub icon_path: ::prost::alloc::string::String,
    #[prost(int32, tag = "7")]
    pub api_version: i32,
    #[prost(string, tag = "8")]
    pub min_nginx_ui_version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub server: ::core::option::Option<ManifestServer>,
    #[prost(message, optional, tag = "10")]
    pub webapp: ::core::option::Option<ManifestWebapp>,
    #[prost(message, optional, tag = "11")]
    pub content: ::core::option::Option<ManifestContent>,
    #[prost(string, repeated, tag = "12")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "13")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "14")]
    pub requires: ::prost::alloc::vec::Vec<ManifestRequirement>,
    #[prost(string, repeated, tag = "15")]
    pub requires_capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "16")]
    pub events: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "17")]
    pub cron: ::prost::alloc::vec::Vec<ManifestCron>,
    #[prost(string, repeated, tag = "18")]
    pub network_hosts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "19")]
    pub dns01: ::core::option::Option<ManifestDns01>,
    #[prost(message, optional, tag = "20")]
    pub http: ::core::option::Option<ManifestHttp>,
    #[prost(message, optional, tag = "21")]
    pub settings_schema: ::core::option::Option<SettingsSchema>,
    #[prost(message, optional, tag = "22")]
    pub notify: ::core::option::Option<ManifestNotify>,
    #[prost(message, optional, tag = "23")]
    pub probe: ::core::option::Option<ManifestProbe>,
    #[prost(message, optional, tag = "24")]
    pub mcp: ::core::option::Option<ManifestMcp>,
    #[prost(message, optional, tag = "25")]
    pub storage: ::core::option::Option<ManifestStorage>,
    #[prost(message, optional, tag = "26")]
    pub deploy: ::core::option::Option<ManifestDeploy>,
    #[prost(message, optional, tag = "27")]
    pub blocklist: ::core::option::Option<ManifestBlocklist>,
    #[prost(message, optional, tag = "28")]
    pub discovery: ::core::option::Option<ManifestDiscovery>,
    #[prost(message, optional, tag = "29")]
    pub log_sink: ::core::option::Option<ManifestLogSink>,
    #[prost(btree_map = "string, message", tag = "30")]
    pub i18n: ::prost::alloc::collections::BTreeMap<::prost::alloc::string::String, ManifestI18n>,
    #[prost(string, repeated, tag = "31")]
    pub conflicts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(btree_map = "string, string", tag = "32")]
    pub permission_reasons: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, repeated, tag = "33")]
    pub screenshots: ::prost::alloc::vec::Vec<ManifestScreenshot>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ManifestScreenshot {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub dark_path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub caption: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManifestI18n {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "3")]
    pub permission_reasons: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(btree_map = "string, string", tag = "4")]
    pub screenshot_captions: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManifestServer {
    #[prost(btree_map = "string, string", tag = "1")]
    pub executables: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, repeated, tag = "2")]
    pub command: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub lifecycle: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub idle_timeout_seconds: i32,
    #[prost(message, optional, tag = "5")]
    pub resources: ::core::option::Option<ManifestResources>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ManifestResources {
    #[prost(int32, tag = "1")]
    pub memory_mb: i32,
    #[prost(int32, tag = "2")]
    pub cpu_percent: i32,
    #[prost(int32, tag = "3")]
    pub recommended_memory_mb: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManifestWebapp {
    #[prost(string, tag = "1")]
    pub bundle_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub style_path: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "3")]
    pub shared: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, repeated, tag = "4")]
    pub pages: ::prost::alloc::vec::Vec<ManifestPage>,
    #[prost(btree_map = "string, string", tag = "5")]
    pub chunks: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManifestPage {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub title: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "3")]
    pub icon: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub file: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ManifestContent {
    #[prost(string, tag = "1")]
    pub templates: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub locales: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ManifestRequirement {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ManifestCron {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub schedule: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub method: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManifestDns01 {
    #[prost(message, repeated, tag = "1")]
    pub providers: ::prost::alloc::vec::Vec<Dns01Provider>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dns01Provider {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub links: ::core::option::Option<Dns01ProviderLinks>,
    #[prost(int32, tag = "5")]
    pub propagation_timeout_seconds: i32,
    #[prost(int32, tag = "6")]
    pub polling_interval_seconds: i32,
    #[prost(message, optional, tag = "7")]
    pub form: ::core::option::Option<Dns01ProviderForm>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Dns01ProviderLinks {
    #[prost(string, tag = "1")]
    pub api: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dns01ProviderForm {
    #[prost(message, repeated, tag = "1")]
    pub fields: ::prost::alloc::vec::Vec<Dns01ProviderField>,
    #[prost(message, repeated, tag = "2")]
    pub methods: ::prost::alloc::vec::Vec<Dns01ProviderMethod>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Dns01ProviderField {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub label: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub help: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub group: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub optional: bool,
    #[prost(bool, tag = "6")]
    pub secret: bool,
    #[prost(string, tag = "7")]
    pub default: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub unit: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub link: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dns01ProviderMethod {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub recommended: bool,
    #[prost(string, repeated, tag = "3")]
    pub fields: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(btree_map = "string, string", tag = "4")]
    pub values: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ManifestHttp {
    #[prost(string, tag = "1")]
    pub listen: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManifestNotify {
    #[prost(message, repeated, tag = "1")]
    pub channels: ::prost::alloc::vec::Vec<NotifyChannel>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotifyChannel {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub configuration: ::core::option::Option<ConfigurationSchema>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManifestProbe {
    #[prost(message, repeated, tag = "1")]
    pub kinds: ::prost::alloc::vec::Vec<ProbeKind>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProbeKind {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub configuration: ::core::option::Option<ConfigurationSchema>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManifestStorage {
    #[prost(message, repeated, tag = "1")]
    pub backends: ::prost::alloc::vec::Vec<StorageBackend>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageBackend {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub configuration: ::core::option::Option<ConfigurationSchema>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManifestDeploy {
    #[prost(message, repeated, tag = "1")]
    pub targets: ::prost::alloc::vec::Vec<DeployTarget>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeployTarget {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub configuration: ::core::option::Option<ConfigurationSchema>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManifestBlocklist {
    #[prost(message, repeated, tag = "1")]
    pub sources: ::prost::alloc::vec::Vec<BlocklistSource>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlocklistSource {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub configuration: ::core::option::Option<ConfigurationSchema>,
    #[prost(int32, tag = "4")]
    pub refresh_seconds: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManifestDiscovery {
    #[prost(message, repeated, tag = "1")]
    pub providers: ::prost::alloc::vec::Vec<DiscoveryProvider>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoveryProvider {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub configuration: ::core::option::Option<ConfigurationSchema>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ManifestLogSink {
    #[prost(int32, tag = "1")]
    pub batch_size: i32,
    #[prost(int32, tag = "2")]
    pub flush_interval_ms: i32,
    #[prost(string, repeated, tag = "3")]
    pub formats: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigurationSchema {
    #[prost(message, repeated, tag = "1")]
    pub fields: ::prost::alloc::vec::Vec<ConfigurationField>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfigurationField {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub help_text: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub required: bool,
    #[prost(bool, tag = "6")]
    pub secret: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManifestMcp {
    #[prost(message, repeated, tag = "1")]
    pub tools: ::prost::alloc::vec::Vec<McpTool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McpTool {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub input_schema: ::core::option::Option<crate::pb::wkt::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SettingsSchema {
    #[prost(string, tag = "1")]
    pub header: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub footer: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub settings: ::prost::alloc::vec::Vec<SettingsField>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SettingsField {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub help_text: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub default: ::core::option::Option<crate::pb::wkt::Value>,
    #[prost(message, repeated, tag = "6")]
    pub options: ::prost::alloc::vec::Vec<SettingsOption>,
    #[prost(bool, tag = "7")]
    pub required: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SettingsOption {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub label: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McpCallRequest {
    #[prost(string, tag = "1")]
    pub tool: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub arguments: ::core::option::Option<crate::pb::wkt::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McpCallResponse {
    #[prost(message, repeated, tag = "1")]
    pub content: ::prost::alloc::vec::Vec<McpContent>,
    #[prost(bool, tag = "2")]
    pub is_error: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpContent {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotifySendRequest {
    #[prost(string, tag = "1")]
    pub channel: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "3")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub severity: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifySendResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotifyValidateRequest {
    #[prost(string, tag = "1")]
    pub channel: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifyValidateResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProbeCheckRequest {
    #[prost(string, tag = "1")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "3")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(int32, tag = "4")]
    pub timeout_seconds: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProbeCheckResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub latency_ms: i32,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageValidateRequest {
    #[prost(string, tag = "1")]
    pub backend: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageValidateResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StoragePutRequest {
    #[prost(string, tag = "1")]
    pub backend: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub source_path: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StoragePutResponse {
    #[prost(double, tag = "1")]
    pub size: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageGetRequest {
    #[prost(string, tag = "1")]
    pub backend: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub target_path: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StorageGetResponse {
    #[prost(double, tag = "1")]
    pub size: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageListRequest {
    #[prost(string, tag = "1")]
    pub backend: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "3")]
    pub prefix: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageListResponse {
    #[prost(message, repeated, tag = "1")]
    pub objects: ::prost::alloc::vec::Vec<StorageObject>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageObject {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub size: f64,
    #[prost(string, tag = "3")]
    pub modified_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageDeleteRequest {
    #[prost(string, tag = "1")]
    pub backend: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub config: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageDeleteResponse {}
